### ISSUE TITLE
How can we capture Request Payload & Response Json and show them to jest-html-reporter for REST API Automation framework?

### ISSUE THREAD

**Issue by ersinghrajkr** [jest-community/awesome-jest#128]
How can we capture Request Payload & Response Json and show them to jest-html-reporter for REST API Automation Framework
using supertest and jest with typescript.

**Comment by mrazauskas** [comment]
`awesome-jest` repository is just a list of Jest packages and resources. Each package is maintained in its own repo. For instance, you can find `jest-html-reporter` in: https://github.com/Hargne/jest-html-reporter. That’s the right place to ask question like yours.
