### ISSUE TITLE
Can we have an entry in the list for @testdeck/jest?

### ISSUE THREAD

**Issue by silkentrance** [jest-community/awesome-jest#53]
We have created a wrapper for existing test frameworks, including also jest.
Please see https://github.com/testdeck/testdeck and also https://github.com/testdeck/testdeck-jest-seed for a working minimal setup.

However, I do not know where to place the entry in the existing list of packages since we are basically a wrapper using decorators so that you can author test suites and tests thereof in an object oriented way.

**Comment by SimenB** [comment]
Sure! Please open up a PR and we'll merge it 🙂 Id there's no fitting section, just create a new one

**Comment by jeysal** [comment]
Maybe "library extensions"?

**Comment by silkentrance** [comment]
@SimenB @jeysal Great, thank you very much. I will prepare a PR for this in the upcoming days.

**Comment by silkentrance** [comment]
👍
