### ISSUE TITLE
jest test ts mocking

### ISSUE THREAD

**Issue by swana1337** [jest-community/awesome-jest#93]
can please anyone explain me how to test the four bold lines ? i really don't know i just wrote this test:

jest.mock('../middleware/i18n');
const mockedFunction = changeLanguage as jest.MockedFunction

describe("i18n", () => {
test("language is set to en", async () => {
var i18n = new I18n();
i18n.setLocale("en");
changeLanguage(i18n);
logger.info(mockedFunction);
expect(mockedFunction).toBeCalledTimes(1);
expect(mockedFunction).toBeCalledWith(i18n);
});
});

buuut, it only covers the first two lines of the following code.

export function changeLanguage(i18n: I18n) {
return (req, res, next) => {
const locale = ((req.query.locale as string) || "de-AT").split("-")[0];
req.setLocale(locale.split("-")[0]);
res.locals.lang = i18n.getLocale(req)
next();
};
}

i hope anybody could help me. Pleaseee. Thank you. :)

**Comment by SimenB** [comment]
This repo is not for questions. You should try out [StackOverflow](https://stackoverflow.com/questions/tagged/jestjs) or our [discord channel](https://discord.gg/j6FKKQQrW9) for questions.
